Ask for deploy settings
frontend/generator-toolbox pull request #84
Opened 2017-08-04 08:26 UTC by tonifisler

We need that because the deploy script is run from the `node_modules/toolbox-utils` directory, which would make it deploy to the wrong repository.

2017-08-16 15:05 UTC, Yago requested changes
I think we have to be more open than only Antistatique's repository 😅

2017-08-16 15:05 UTC, Yago commented on generators/app/index.js
> +        default: function (answers) {
You ask for the full URL and you concat it with Antistatique organisation repo url ? 🤔  Not sure to understand this one....

2017-08-16 15:05 UTC, Yago commented on generators/app/templates/_package.json
> +    "deploy": "toolbox build styleguide && toolbox deploy"
Because we are asking it, we can also add the repo url in the `package.json`

2017-08-17 06:39 UTC, tonifisler commented on generators/app/index.js
> +        default: function (answers) {
In the `default` below? That's the default value, you can change it in the prompt

2017-08-18 05:31 UTC, tonifisler commented
@Yago RTBM

2017-09-13 11:45 UTC, merged